#
# this version of docker-compose can only be used up to version 1.6.n of docker-compose (docker 1.10.n+)
#
# copy this file to your source root and execute: 'docker-compose up -d jira'
# inside your terminal.
#
# our jira service container
#
version: '2'
services:
  confluence:
    restart: 'always'
    # image: df/dunkelfrosch-confluence
    build:
      context: .

    container_name: df-atls-confluence

    ports:
      - "8090:8090"

    privileged: false
    stdin_open: true
    tty: true
